### ISSUE TITLE
Missing definition for get_articulated_object_root_state()

### ISSUE THREAD

**Issue by RAraghavarora** [yashkant/housekeep#5]
I need some help while setting up the Housekeep repository.

While trying to run the code to create different scenes with rearranged objects using Housekeep, the functions `get_articulated_object_root_state(object_id)`, and `set_articulated_object_root_state(object_id)` have been used which are not defined in the Housekeep sourcecode, nor in the HabitatSim sourcecode. Where is the function definition available?

For certain objects, the sim_obj_id obtained is -1, and pdb has been added for the same. What is the reason for negative sim_obj_id, how can it be avoided?

Thank you in advance

**Comment by JHurricane96** [comment]
Hey @RAraghavarora, could you share the script from the repo that you ran? Was it [this one](https://github.com/yashkant/housekeep/blob/master/cos_eor/scripts/build_cos_eor_dataset_v3.py)?

**Comment by RAraghavarora** [comment]
> Hey @RAraghavarora, could you share the script from the repo that you ran? Was it [this one](https://github.com/yashkant/housekeep/blob/master/cos_eor/scripts/build_cos_eor_dataset_v3.py)?

Hello @JHurricane96 , I tried multiple scripts, starting with [hie_policy_runner](https://github.com/yashkant/housekeep/blob/master/run_cli.sh) as mentioned in the project readme. 

Apart from this, every time I create and reset habitat environment, I get these errors:
```
config = habitat.get_config(config_path)
config = habitat.get_config_new([config.BASE_TASK_CONFIG])
env = habitat.Env(config)
env.reset()
```

**Comment by yashkant** [comment]
hey @RAraghavarora, 

could you try reinstalling the simulator from this branch: https://github.com/yashkant/habitat-sim/tree/latest-2/

I can confirm that it has both the needed methods [https://github.com/yashkant/habitat-sim/blob/latest-2/src/esp/sim/Simulator.cpp#L1485]. 

please let me know how it goes.  apologies, for the trouble and delay!

**Comment by JHurricane96** [comment]
@RAraghavarora before trying Yash's solution, could you run a few commands in the debugger you were dropped into? The `obj_id` is usually -1 when the object config file is missing from the dataset and so the simulator is unable to load it.
```
n
p file
```
This should take you one level up the execution stack and give you the name of the missing file. I suspect it's from the Amazon Berkeley dataset (the file will start with `data/amazon-berkeley` if this is indeed the case). The [instructions to set up the dataset](https://github.com/yashkant/housekeep/blob/master/data/README.md) had mentioned to run [this script](https://github.com/yashkant/housekeep/blob/master/cos_eor/scripts/ab_objects_viz.py) to create the object config files for the Amazon Berkeley objects. I found out there was a bug with this script -- you might have run this earlier and not noticed that it was throwing an error. I've now pushed a fix for this. If your missing object is from the Amazon Berkeley dataset, then pull from master and try running this script again. The baselines should then run.

Let us know if you run into any other issues!

**Comment by adata111** [comment]
> 

Thanks a lot, @JHurricane96 ! Yes, we were missing the amazon-berkeley dataset. Following your advice, the object_id -1 issue was resolved.

> @RAraghavarora before trying Yash's solution, could you run a few commands in the debugger you were dropped into? The `obj_id` is usually -1 when the object config file is missing from the dataset and so the simulator is unable to load it.
> 
> ```
> n
> p file
> ```
> 
> This should take you one level up the execution stack and give you the name of the missing file. I suspect it's from the Amazon Berkeley dataset (the file will start with `data/amazon-berkeley` if this is indeed the case). The [instructions to set up the dataset](https://github.com/yashkant/housekeep/blob/master/data/README.md) had mentioned to run [this script](https://github.com/yashkant/housekeep/blob/master/cos_eor/scripts/ab_objects_viz.py) to create the object config files for the Amazon Berkeley objects. I found out there was a bug with this script -- you might have run this earlier and not noticed that it was throwing an error. I've now pushed a fix for this. If your missing object is from the Amazon Berkeley dataset, then pull from master and try running this script again. The baselines should then run.
> 
> Let us know if you run into any other issues!

**Comment by adata111** [comment]
Hi @yashkant thanks for your response! We tried re-installing habitat-sim from the repo you mentioned. However, we are still facing some issues. On running `./run_cli.sh test pomaria_1_int 2` we are getting the following error:
    `AttributeError: 'ExploreSim' object has no attribute 'get_rigid_object_manager`

Do you have any insights on how to go about this error?
> hey @RAraghavarora,
> 
> could you try reinstalling the simulator from this branch: https://github.com/yashkant/habitat-sim/tree/latest-2/
> 
> I can confirm that it has both the needed methods [https://github.com/yashkant/habitat-sim/blob/latest-2/src/esp/sim/Simulator.cpp#L1485].
> 
> please let me know how it goes. apologies, for the trouble and delay!

**Comment by JHurricane96** [comment]
Hello @adata111,

I'd recommend you stick with the version of habitat sim mentioned in the README (`0.2.1`). I know Yash suggested using the one on his fork, but that was when we thought the object id issue was related to the habitat sim version and not the missing Amazon Berkeley objects. Installing it via conda as mentioned in the README should fix the `get_rigid_object_manager` error.

**Comment by adata111** [comment]
Hi @JHurricane96 
We tried installing habitat-sim 0.2.1, but it's giving the following error:
`'ExploreSim' object has no attribute 'get_articulated_object_root_state'`

**Comment by JHurricane96** [comment]
This is strange since we don't have any articulated objects in our dataset, so I'm surprised you're running into this error. I'm able to run the baselines fine on my end too. Could you share the script you were running and a stack trace of when you run into this error? Also if you're dropped into a debugger, could you share the object ID and and the file name of the object following the steps I'd outlined earlier?

**Comment by Ayush8120** [comment]
Hey Arun!
I'm afraid that the issue is not with the habitat-sim. We still are getting `sim_obj_id as -1` in the pdb. It may be due to the fact that we had to change the data directory's location due to memory constraints. We tried to be careful to update the data path directory everywhere(to our best knowledge), but we still face this issue when we execute `./run_cli.sh ayush-proper-1 ihlen_1_int 2`
 
```
E0203 13:38:15.903034  5348 ManagedContainerBase.h:331] <Object Template>::getObjectCopyByHandle : Unknown Object Template managed object handle :/scratch/ahana/housekeep/housekeep-data/data/data/google_object_dataset/Threshold_Porcelain_Spoon_Rest_White/meshes/Threshold_Porcelain_Spoon_Rest_White.object_config.json. Aborting
E0203 13:38:15.903048  5348 PhysicsManager.h:338] ::addObject : Object creation failed due to unknown attributes /scratch/ahana/housekeep/housekeep-data/data/data/google_object_dataset/Threshold_Porcelain_Spoon_Rest_White/meshes/Threshold_Porcelain_Spoon_Rest_White.object_config.json
```
We are then dropped into the debugger.

We feel there are still some places where we might have to update the data directory's path.

**Comment by JHurricane96** [comment]
Have you followed all the instructions in [this page](https://github.com/yashkant/housekeep/blob/master/data/README.md)? From the errors you posted, it looks like you're not able to locate the Google Scanned Objects. If you haven't already, you should ensure that your data directory follows the structure outlined in that page.

Rather than updating the code to point to new data directories, it would probably be simpler to create symlinks from the `data/` folder to all the asset locations you need.

**Comment by Ayush8120** [comment]
Thanks a lot for your help, Arun and Yash! It's working! 

Just a slight doubt, will the performance be affected if we don't downscale the assets? because running the `downscale_assets.py` throws this error

```
struct.error: unpack_from requires a buffer of at least 4 bytes

The above exception was the direct cause of the following exception:
Traceback (most recent call last):
  File "downscale_assets.py", line 29, in <module>
    for f in tqdm(files):
  File "/home2/ahana/miniconda3/envs/habitat2/lib/python3.7/site-packages/PIL/Image.py", line 1982, in resize
    self.load()
  File "/home2/ahana/miniconda3/envs/habitat2/lib/python3.7/site-packages/PIL/ImageFile.py", line 243, in load
    raise OSError("image file is truncated") from e
OSError: image file is truncated
```

**Comment by JHurricane96** [comment]
Glad to hear that you've got it working! I'm not sure what the error you're getting now is caused by, perhaps the textures got corrupted while downloading them? I don't remember us facing this error. The simulator will be much slower if you use the full-sized textures, so if you're only facing this for some objects, then you could modify the script to skip over just those.
